version: "{build}"

os: Visual Studio 2015

environment:
  matrix:
    - generator: Visual Studio 14 2015 Win64
      ARCH: x64
      SHARED_LIBS: OFF
    - generator: Visual Studio 14 2015
      ARCH: x86
      SHARED_LIBS: OFF
    # - generator: MinGW Makefiles
    #   CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #   ARCH: x86
    #   SHARED_LIBS: OFF
    - generator: Visual Studio 14 2015 Win64
      ARCH: x64
      SHARED_LIBS: ON
    - generator: Visual Studio 14 2015
      ARCH: x86
      SHARED_LIBS: ON
    # - generator: MinGW Makefiles
    #   CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
    #   ARCH: x86
    #   SHARED_LIBS: ON

configuration:
  - Debug

clone_depth: 10
clone_folder: c:\chemfiles

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true


# Uncomment the following lines to enable remote desktop access to Appveyor
# after a failed build.

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_failure:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: . .\scripts\ci\setup-appveyor.ps1

build_script:
  - cd C:\chemfiles
  - mkdir build
  - cd build
  - ps: echo $env:CMAKE_ARGUMENTS
  - cmake %CMAKE_ARGUMENTS% ..
  - cmake --build . --config "%configuration%" -- %BUILD_ARGUMENTS%

test_script:
  - ctest --build-config "%configuration%" --timeout 300 --output-on-failure
